### ISSUE TITLE
Compiler issue because of using id as "file:///C:/" 

### ISSUE THREAD

**Issue by sowmiyaksr** [atomicbits/scraml-test-scala#4]
Hi,

Thanks for the reply and solution.

I changed the plugins.sbt with the new version.

And getting the error on package names.

For json schema files, I canged the "id" field to 
point local files, since the "id" : "http:atomicbits.io/..."
is not available.

Please find attached the screenshot of the error.
![scramlerror](https://cloud.githubusercontent.com/assets/24889962/21763638/e05d3f6c-d684-11e6-9528-fec958dd49d3.png)

**Comment by rigolepe** [comment]
Hello,

What error do you see if you keep the "id" fields at their original value? It doesn't matter if they don't resolve because they are just IDs, scraml will not fetch those files online.

If the same error persists, or another comes up, then I'll have to test it on cygwin myself.

**Comment by sowmiyaksr** [comment]
Great. Thanks. I keep the same id value. Now I dont get any error.

Thanks.

**Comment by rigolepe** [comment]
OK, thanks for testing!
